using Miniblog.Models.App.Interfaces;
using Miniblog.Models.Entities;
using Miniblog.Models.Services.Interfaces;
using Miniblog.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Cryptography;
using System.Text;

namespace Miniblog.Models.App
{
    public class UserService : IUserService
    {
        public IRepository _repository { get; private set; }
        public UserService(IRepository repository)
        {
            _repository = repository;
        }
        /// <summary>
        /// Checks if users with same emails or usernames are already exists in database.
        /// </summary>
        /// <param name="registerModel"></param>
        /// <returns>List of errors.</returns>
        public IEnumerable<string> ParametersAlreadyExist(RegisterViewModel registerModel)
        {
            var sameUsername = _repository.Users.Find(u => u.Username == registerModel.Username);
            var sameEmail = _repository.Users.Find(u => u.Email == registerModel.Email);
            IEnumerable<string> errors = new List<string>();
            if(sameUsername.Any())
            {
                errors.Append("Username");
            }
            if(sameEmail.Any())
            {
                errors.Append("Email");
            }
            return errors;
        }
        /// <summary>
        /// Retrieves the hash from the password, gives plain user role and puts new user into database.
        /// </summary>
        /// <param name="registerModel"></param>
        /// <returns>New user object</returns>
        public async Task<User> CreateIntoDbAsync(RegisterViewModel registerModel)
        {
            // проверка (есть ли др. пользователи) происходит до выполнения этого метода
            User newUser = ToUser(registerModel);

            await _repository.Users.CreateAsync(newUser);
            User user = _repository.Users.Find(u => u.Email == newUser.Email && u.Hash == newUser.Hash).First(); // user with Id generated by db
            return user;
        }
        private string GetHash(string password)
        {
            byte[] pass = Encoding.UTF8.GetBytes(password);
            string hash;
            using (SHA256 sha = SHA256.Create())
            {
                byte[] fromPass = sha.ComputeHash(pass);
                hash = Encoding.UTF8.GetString(fromPass);
            }
            return hash;
        }
        private User ToUser(RegisterViewModel registerModel)
        {
            Role userRole = _repository.Roles.Find(r=> r.Type == Entities.Enums.RoleType.User).First();

            User newUser = new User()
            {
                Username = registerModel.Username,
                Email = registerModel.Email,
                RoleId = userRole.Id,
                Role = userRole,
                Hash = GetHash(registerModel.Password),
                DateOfRegistration = DateTimeOffset.UtcNow
            };

            return newUser;
        }
        public User GetFromDb(LoginViewModel loginModel)
        {
            string hash = GetHash(loginModel.Password);
            var user = _repository.Users.Find(u => u.Username == loginModel.Username && u.Hash == hash).First();
            return user;
        }

        public bool CheckForExistence(RegisterViewModel registerModel, Guid guid)
        {
            string hash = GetHash(registerModel.Password);
            var user = _repository.Users.Find(u => u.Username == registerModel.Username
                && u.Email == registerModel.Email
                && u.Hash == hash
                && u.Id == guid)
                .FirstOrDefault();
            if(user != null)
            {
                return true;
            }
            return false;
        }

        public bool CheckForExistence(LoginViewModel loginModel, Guid guid)
        {
            string hash = GetHash(loginModel.Password);
            var user = _repository.Users.Find(u => u.Username == loginModel.Username
                && u.Hash == hash
                && u.Id == guid)
                .FirstOrDefault();
            if (user != null)
            {
                return true;
            }
            return false;
        }

        public async Task<User> GetFromDbAsync(Guid id)
        {
            return await _repository.Users.GetByIdAsync(id);
        }

        public async Task PutRefreshTokenIntoDb(User user, string refreshToken, DateTimeOffset expiration)
        {
            RefreshToken token = new RefreshToken()
            {
                User = user,
                AccessTokenExpiration = expiration,
                Token = refreshToken
            };
            await _repository.RefreshTokens.CreateAsync(token);
        }
    }
}
